package com.hivemc.chunker.downgrade;

import com.hivemc.chunker.conversion.handlers.ColumnConversionHandler;
import com.hivemc.chunker.conversion.intermediate.column.ChunkerColumn;
import com.hivemc.chunker.conversion.intermediate.column.blockentity.BlockEntity;
import com.hivemc.chunker.conversion.intermediate.column.chunk.ChunkerChunk;
import com.hivemc.chunker.conversion.intermediate.column.chunk.RegionCoordPair;
import com.hivemc.chunker.conversion.intermediate.column.entity.Entity;

import java.util.ArrayList;
import java.util.List;

/**
 * Moves every column upwards, before the writer ever sees it.
 * <p>
 * Worlds generated by 1.18 and later can extend down to Y=-64, but the 1.12.2 format only addresses sections 0
 * to 15. Anything outside that window is dropped by the writer without warning, so a modern world converted
 * as-is comes out completely empty. Shifting is therefore not a nicety - it is the difference between a map and
 * a blank world.
 *
 * The shift is always a whole number of sections, which means a column's sections are simply re-labelled rather
 * than rebuilt. Two things fall out of doing it this way: no block data is copied or re-encoded, and the
 * per-section light arrays travel along with their section instead of ending up attached to the wrong height.
 *
 * Entities and block entities hold absolute co-ordinates of their own, so they are moved by the same amount -
 * otherwise every chest, sign and painting would drift away from the structure it belongs to.
 */
public class ShiftColumnHandler implements ColumnConversionHandler {
    private final ColumnConversionHandler delegate;
    private final int shiftSections;
    private final int shiftY;
    private final int minSectionY;
    private final int maxSectionY;
    private final ShiftStats stats;

    /**
     * Create a new shifting handler.
     *
     * @param delegate      the next handler in the pipeline.
     * @param shiftSections how many sections to move every column up by.
     * @param minSectionY   the lowest section index the output format can store.
     * @param maxSectionY   the highest section index the output format can store.
     * @param stats         shared counters for anything left behind, so totals span every dimension.
     */
    public ShiftColumnHandler(ColumnConversionHandler delegate, int shiftSections, int minSectionY, int maxSectionY, ShiftStats stats) {
        this.delegate = delegate;
        this.shiftSections = shiftSections;
        this.shiftY = shiftSections * BlockSurvey.SECTION_SIZE;
        this.minSectionY = minSectionY;
        this.maxSectionY = maxSectionY;
        this.stats = stats;
    }

    @Override
    public void convertColumn(ChunkerColumn column) {
        if (shiftSections != 0 || !isWithinBounds(column)) {
            applyShift(column);
        }
        delegate.convertColumn(column);
    }

    @Override
    public void flushRegion(RegionCoordPair regionCoordPair) {
        delegate.flushRegion(regionCoordPair);
    }

    @Override
    public void flushColumns() {
        delegate.flushColumns();
    }

    /**
     * Check whether every section of a column is already inside the writable window.
     */
    private boolean isWithinBounds(ChunkerColumn column) {
        for (ChunkerChunk chunk : column.getChunks().values()) {
            int y = chunk.getY();
            if (y < minSectionY || y > maxSectionY) return false;
        }
        return true;
    }

    /**
     * Move a column's sections and its absolute-positioned contents up by the shift.
     */
    private void applyShift(ChunkerColumn column) {
        // Re-label the sections. The Y of a chunk is the key it is stored under, so entries move between keys;
        // the payload (palette and light) is carried across untouched.
        var chunks = column.getChunks();
        List<ChunkerChunk> surviving = new ArrayList<>(chunks.size());
        for (ChunkerChunk chunk : chunks.values()) {
            int newY = chunk.getY() + shiftSections;
            if (newY < minSectionY || newY > maxSectionY) {
                // Only count a dropped section if it actually held something. A modern world is mostly empty air
                // above its terrain, so counting every discarded section would report tens of thousands of
                // "losses" that cost the user nothing and would bury the ones that matter.
                if (!chunk.isEmpty()) {
                    stats.recordClippedSection();
                }
                continue;
            }
            chunk.setY((byte) newY);
            if (!chunk.isEmpty()) {
                stats.recordShiftedSection();
            }
            surviving.add(chunk);
        }
        chunks.clear();
        for (ChunkerChunk chunk : surviving) {
            chunks.put(chunk.getY(), chunk);
        }

        // Block entities carry their own absolute co-ordinate.
        column.getBlockEntities().removeIf(blockEntity -> {
            int newY = blockEntity.getY() + shiftY;
            if (newY < minSectionY * BlockSurvey.SECTION_SIZE || newY > maxSectionY * BlockSurvey.SECTION_SIZE + BlockSurvey.SECTION_SIZE - 1) {
                stats.recordDroppedBlockEntity();
                return true;
            }
            blockEntity.setY(newY);
            return false;
        });

        // As do entities, at fractional precision.
        column.getEntities().removeIf(entity -> {
            double newY = entity.getPositionY() + shiftY;
            if (newY < minSectionY * BlockSurvey.SECTION_SIZE || newY > maxSectionY * BlockSurvey.SECTION_SIZE + BlockSurvey.SECTION_SIZE) {
                stats.recordDroppedEntity();
                return true;
            }
            entity.setPositionY(newY);
            return false;
        });
    }
}
