webroot: "D:/Vantaloom/data/temp/conv-20260912094016-8df320d6b1/scratch/bluemap-test/web"
maps: [
  {
    id: "converted"
    name: "Converted 1.12.2"
    world: "D:/Vantaloom/data/temp/conv-20260912094016-8df320d6b1/scratch/conv-test/out_1_15_2_to_1_12_2"
    skyColor: "#7dabff"
    ambientLight: 0
    renderCaves: false
    renderEdges: true
    useCompression: false
  }
]